// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $create from "./routes/create.tsx";
import * as $delete from "./routes/delete.tsx";
import * as $hero_name_ from "./routes/hero/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $DeleteHero from "./islands/DeleteHero.tsx";
import * as $FormCreate from "./islands/FormCreate.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/create.tsx": $create,
    "./routes/delete.tsx": $delete,
    "./routes/hero/[name].tsx": $hero_name_,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/DeleteHero.tsx": $DeleteHero,
    "./islands/FormCreate.tsx": $FormCreate,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
